module.exports = [
  {"type":0,"data":0,"description":"Air","name":"minecraft:air"},
  {"type":1,"data":0,"description":"Stone","name":"minecraft:stone"},
  {"type":1,"data":1,"description":"Granite","name":"minecraft:stone"},
  {"type":1,"data":2,"description":"Polished Granite","name":"minecraft:stone"},
  {"type":1,"data":3,"description":"Diorite","name":"minecraft:stone"},
  {"type":1,"data":4,"description":"Polished Diorite","name":"minecraft:stone"},
  {"type":1,"data":5,"description":"Andesite","name":"minecraft:stone"},
  {"type":1,"data":6,"description":"Polished Andesite","name":"minecraft:stone"},
  {"type":2,"data":0,"description":"Grass","name":"minecraft:grass"},
  {"type":3,"data":0,"description":"Dirt","name":"minecraft:dirt"},
  {"type":3,"data":1,"description":"Coarse Dirt","name":"minecraft:dirt"},
  {"type":3,"data":2,"description":"Podzol","name":"minecraft:dirt"},
  {"type":4,"data":0,"description":"Cobblestone","name":"minecraft:cobblestone"},
  {"type":5,"data":0,"description":"Oak Wood Plank","name":"minecraft:planks"},
  {"type":5,"data":1,"description":"Spruce Wood Plank","name":"minecraft:planks"},
  {"type":5,"data":2,"description":"Birch Wood Plank","name":"minecraft:planks"},
  {"type":5,"data":3,"description":"Jungle Wood Plank","name":"minecraft:planks"},
  {"type":5,"data":4,"description":"Acacia Wood Plank","name":"minecraft:planks"},
  {"type":5,"data":5,"description":"Dark Oak Wood Plank","name":"minecraft:planks"},
  {"type":6,"data":0,"description":"Oak Sapling","name":"minecraft:sapling"},
  {"type":6,"data":1,"description":"Spruce Sapling","name":"minecraft:sapling"},
  {"type":6,"data":2,"description":"Birch Sapling","name":"minecraft:sapling"},
  {"type":6,"data":3,"description":"Jungle Sapling","name":"minecraft:sapling"},
  {"type":6,"data":4,"description":"Acacia Sapling","name":"minecraft:sapling"},
  {"type":6,"data":5,"description":"Dark Oak Sapling","name":"minecraft:sapling"},
  {"type":7,"data":0,"description":"Bedrock","name":"minecraft:bedrock"},
  {"type":8,"data":0,"description":"Flowing Water","name":"minecraft:flowing_water"},
  {"type":9,"data":0,"description":"Still Water","name":"minecraft:water"},
  {"type":10,"data":0,"description":"Flowing Lava","name":"minecraft:flowing_lava"},
  {"type":11,"data":0,"description":"Still Lava","name":"minecraft:lava"},
  {"type":12,"data":0,"description":"Sand","name":"minecraft:sand"},
  {"type":12,"data":1,"description":"Red Sand","name":"minecraft:sand"},
  {"type":13,"data":0,"description":"Gravel","name":"minecraft:gravel"},
  {"type":14,"data":0,"description":"Gold Ore","name":"minecraft:gold_ore"},
  {"type":15,"data":0,"description":"Iron Ore","name":"minecraft:iron_ore"},
  {"type":16,"data":0,"description":"Coal Ore","name":"minecraft:coal_ore"},
  {"type":17,"data":0,"description":"Oak Wood","name":"minecraft:log"},
  {"type":17,"data":1,"description":"Spruce Wood","name":"minecraft:log"},
  {"type":17,"data":2,"description":"Birch Wood","name":"minecraft:log"},
  {"type":17,"data":3,"description":"Jungle Wood","name":"minecraft:log"},
  {"type":18,"data":0,"description":"Oak Leaves","name":"minecraft:leaves"},
  {"type":18,"data":1,"description":"Spruce Leaves","name":"minecraft:leaves"},
  {"type":18,"data":2,"description":"Birch Leaves","name":"minecraft:leaves"},
  {"type":18,"data":3,"description":"Jungle Leaves","name":"minecraft:leaves"},
  {"type":19,"data":0,"description":"Sponge","name":"minecraft:sponge"},
  {"type":19,"data":1,"description":"Wet Sponge","name":"minecraft:sponge"},
  {"type":20,"data":0,"description":"Glass","name":"minecraft:glass"},
  {"type":21,"data":0,"description":"Lapis Lazuli Ore","name":"minecraft:lapis_ore"},
  {"type":22,"data":0,"description":"Lapis Lazuli Block","name":"minecraft:lapis_block"},
  {"type":23,"data":0,"description":"Dispenser","name":"minecraft:dispenser"},
  {"type":24,"data":0,"description":"Sandstone","name":"minecraft:sandstone"},
  {"type":24,"data":1,"description":"Chiseled Sandstone","name":"minecraft:sandstone"},
  {"type":24,"data":2,"description":"Smooth Sandstone","name":"minecraft:sandstone"},
  {"type":25,"data":0,"description":"Note Block","name":"minecraft:noteblock"},
  {"type":26,"data":0,"description":"Bed","name":"minecraft:bed"},
  {"type":27,"data":0,"description":"Powered Rail","name":"minecraft:golden_rail"},
  {"type":28,"data":0,"description":"Detector Rail","name":"minecraft:detector_rail"},
  {"type":29,"data":0,"description":"Sticky Piston","name":"minecraft:sticky_piston"},
  {"type":30,"data":0,"description":"Cobweb","name":"minecraft:web"},
  {"type":31,"data":0,"description":"Dead Shrub","name":"minecraft:tallgrass"},
  {"type":31,"data":1,"description":"Grass","name":"minecraft:tallgrass"},
  {"type":31,"data":2,"description":"Fern","name":"minecraft:tallgrass"},
  {"type":32,"data":0,"description":"Dead Bush","name":"minecraft:deadbush"},
  {"type":33,"data":0,"description":"Piston","name":"minecraft:piston"},
  {"type":34,"data":0,"description":"Piston Head","name":"minecraft:piston_head"},
  {"type":35,"data":0,"description":"White Wool","name":"minecraft:wool"},
  {"type":35,"data":1,"description":"Orange Wool","name":"minecraft:wool"},
  {"type":35,"data":2,"description":"Magenta Wool","name":"minecraft:wool"},
  {"type":35,"data":3,"description":"Light Blue Wool","name":"minecraft:wool"},
  {"type":35,"data":4,"description":"Yellow Wool","name":"minecraft:wool"},
  {"type":35,"data":5,"description":"Lime Wool","name":"minecraft:wool"},
  {"type":35,"data":6,"description":"Pink Wool","name":"minecraft:wool"},
  {"type":35,"data":7,"description":"Gray Wool","name":"minecraft:wool"},
  {"type":35,"data":8,"description":"Light Gray Wool","name":"minecraft:wool"},
  {"type":35,"data":9,"description":"Cyan Wool","name":"minecraft:wool"},
  {"type":35,"data":10,"description":"Purple Wool","name":"minecraft:wool"},
  {"type":35,"data":11,"description":"Blue Wool","name":"minecraft:wool"},
  {"type":35,"data":12,"description":"Brown Wool","name":"minecraft:wool"},
  {"type":35,"data":13,"description":"Green Wool","name":"minecraft:wool"},
  {"type":35,"data":14,"description":"Red Wool","name":"minecraft:wool"},
  {"type":35,"data":15,"description":"Black Wool","name":"minecraft:wool"},
  {"type":37,"data":0,"description":"Dandelion","name":"minecraft:yellow_flower"},
  {"type":38,"data":0,"description":"Poppy","name":"minecraft:red_flower"},
  {"type":38,"data":1,"description":"Blue Orchid","name":"minecraft:red_flower"},
  {"type":38,"data":2,"description":"Allium","name":"minecraft:red_flower"},
  {"type":38,"data":3,"description":"Azure Bluet","name":"minecraft:red_flower"},
  {"type":38,"data":4,"description":"Red Tulip","name":"minecraft:red_flower"},
  {"type":38,"data":5,"description":"Orange Tulip","name":"minecraft:red_flower"},
  {"type":38,"data":6,"description":"White Tulip","name":"minecraft:red_flower"},
  {"type":38,"data":7,"description":"Pink Tulip","name":"minecraft:red_flower"},
  {"type":38,"data":8,"description":"Oxeye Daisy","name":"minecraft:red_flower"},
  {"type":39,"data":0,"description":"Brown Mushroom","name":"minecraft:brown_mushroom"},
  {"type":40,"data":0,"description":"Red Mushroom","name":"minecraft:red_mushroom"},
  {"type":41,"data":0,"description":"Gold Block","name":"minecraft:gold_block"},
  {"type":42,"data":0,"description":"Iron Block","name":"minecraft:iron_block"},
  {"type":43,"data":0,"description":"Double Stone Slab","name":"minecraft:double_stone_slab"},
  {"type":43,"data":1,"description":"Double Sandstone Slab","name":"minecraft:double_stone_slab"},
  {"type":43,"data":2,"description":"Double Wooden Slab","name":"minecraft:double_stone_slab"},
  {"type":43,"data":3,"description":"Double Cobblestone Slab","name":"minecraft:double_stone_slab"},
  {"type":43,"data":4,"description":"Double Brick Slab","name":"minecraft:double_stone_slab"},
  {"type":43,"data":5,"description":"Double Stone Brick Slab","name":"minecraft:double_stone_slab"},
  {"type":43,"data":6,"description":"Double Nether Brick Slab","name":"minecraft:double_stone_slab"},
  {"type":43,"data":7,"description":"Double Quartz Slab","name":"minecraft:double_stone_slab"},
  {"type":44,"data":0,"description":"Stone Slab","name":"minecraft:stone_slab"},
  {"type":44,"data":1,"description":"Sandstone Slab","name":"minecraft:stone_slab"},
  {"type":44,"data":2,"description":"Wooden Slab","name":"minecraft:stone_slab"},
  {"type":44,"data":3,"description":"Cobblestone Slab","name":"minecraft:stone_slab"},
  {"type":44,"data":4,"description":"Brick Slab","name":"minecraft:stone_slab"},
  {"type":44,"data":5,"description":"Stone Brick Slab","name":"minecraft:stone_slab"},
  {"type":44,"data":6,"description":"Nether Brick Slab","name":"minecraft:stone_slab"},
  {"type":44,"data":7,"description":"Quartz Slab","name":"minecraft:stone_slab"},
  {"type":45,"data":0,"description":"Bricks","name":"minecraft:brick_block"},
  {"type":46,"data":0,"description":"TNT","name":"minecraft:tnt"},
  {"type":47,"data":0,"description":"Bookshelf","name":"minecraft:bookshelf"},
  {"type":48,"data":0,"description":"Moss Stone","name":"minecraft:mossy_cobblestone"},
  {"type":49,"data":0,"description":"Obsidian","name":"minecraft:obsidian"},
  {"type":50,"data":0,"description":"Torch","name":"minecraft:torch"},
  {"type":51,"data":0,"description":"Fire","name":"minecraft:fire"},
  {"type":52,"data":0,"description":"Monster Spawner","name":"minecraft:mob_spawner"},
  {"type":53,"data":0,"description":"Oak Wood Stairs","name":"minecraft:oak_stairs"},
  {"type":54,"data":0,"description":"Chest","name":"minecraft:chest"},
  {"type":55,"data":0,"description":"Redstone Wire","name":"minecraft:redstone_wire"},
  {"type":56,"data":0,"description":"Diamond Ore","name":"minecraft:diamond_ore"},
  {"type":57,"data":0,"description":"Diamond Block","name":"minecraft:diamond_block"},
  {"type":58,"data":0,"description":"Crafting Table","name":"minecraft:crafting_table"},
  {"type":59,"data":0,"description":"Wheat Crops","name":"minecraft:wheat"},
  {"type":60,"data":0,"description":"Farmland","name":"minecraft:farmland"},
  {"type":61,"data":0,"description":"Furnace","name":"minecraft:furnace"},
  {"type":62,"data":0,"description":"Burning Furnace","name":"minecraft:lit_furnace"},
  {"type":63,"data":0,"description":"Standing Sign Block","name":"minecraft:standing_sign"},
  {"type":64,"data":0,"description":"Oak Door Block","name":"minecraft:wooden_door"},
  {"type":65,"data":0,"description":"Ladder","name":"minecraft:ladder"},
  {"type":66,"data":0,"description":"Rail","name":"minecraft:rail"},
  {"type":67,"data":0,"description":"Cobblestone Stairs","name":"minecraft:stone_stairs"},
  {"type":68,"data":0,"description":"Wall-mounted Sign Block","name":"minecraft:wall_sign"},
  {"type":69,"data":0,"description":"Lever","name":"minecraft:lever"},
  {"type":70,"data":0,"description":"Stone Pressure Plate","name":"minecraft:stone_pressure_plate"},
  {"type":71,"data":0,"description":"Iron Door Block","name":"minecraft:iron_door"},
  {"type":72,"data":0,"description":"Wooden Pressure Plate","name":"minecraft:wooden_pressure_plate"},
  {"type":73,"data":0,"description":"Redstone Ore","name":"minecraft:redstone_ore"},
  {"type":74,"data":0,"description":"Glowing Redstone Ore","name":"minecraft:lit_redstone_ore"},
  {"type":75,"data":0,"description":"Redstone Torch (off)","name":"minecraft:unlit_redstone_torch"},
  {"type":76,"data":0,"description":"Redstone Torch (on)","name":"minecraft:redstone_torch"},
  {"type":77,"data":0,"description":"Stone Button","name":"minecraft:stone_button"},
  {"type":78,"data":0,"description":"Snow","name":"minecraft:snow_layer"},
  {"type":79,"data":0,"description":"Ice","name":"minecraft:ice"},
  {"type":80,"data":0,"description":"Snow Block","name":"minecraft:snow"},
  {"type":81,"data":0,"description":"Cactus","name":"minecraft:cactus"},
  {"type":82,"data":0,"description":"Clay","name":"minecraft:clay"},
  {"type":83,"data":0,"description":"Sugar Canes","name":"minecraft:reeds"},
  {"type":84,"data":0,"description":"Jukebox","name":"minecraft:jukebox"},
  {"type":85,"data":0,"description":"Oak Fence","name":"minecraft:fence"},
  {"type":86,"data":0,"description":"Pumpkin","name":"minecraft:pumpkin"},
  {"type":87,"data":0,"description":"Netherrack","name":"minecraft:netherrack"},
  {"type":88,"data":0,"description":"Soul Sand","name":"minecraft:soul_sand"},
  {"type":89,"data":0,"description":"Glowstone","name":"minecraft:glowstone"},
  {"type":90,"data":0,"description":"Nether Portal","name":"minecraft:portal"},
  {"type":91,"data":0,"description":"Jack o'Lantern","name":"minecraft:lit_pumpkin"},
  {"type":92,"data":0,"description":"Cake Block","name":"minecraft:cake"},
  {"type":93,"data":0,"description":"Redstone Repeater Block (off)","name":"minecraft:unpowered_repeater"},
  {"type":94,"data":0,"description":"Redstone Repeater Block (on)","name":"minecraft:powered_repeater"},
  {"type":95,"data":0,"description":"White Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":1,"description":"Orange Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":2,"description":"Magenta Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":3,"description":"Light Blue Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":4,"description":"Yellow Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":5,"description":"Lime Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":6,"description":"Pink Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":7,"description":"Gray Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":8,"description":"Light Gray Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":9,"description":"Cyan Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":10,"description":"Purple Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":11,"description":"Blue Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":12,"description":"Brown Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":13,"description":"Green Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":14,"description":"Red Stained Glass","name":"minecraft:stained_glass"},
  {"type":95,"data":15,"description":"Black Stained Glass","name":"minecraft:stained_glass"},
  {"type":96,"data":0,"description":"Wooden Trapdoor","name":"minecraft:trapdoor"},
  {"type":97,"data":0,"description":"Stone Monster Egg","name":"minecraft:monster_egg"},
  {"type":97,"data":1,"description":"Cobblestone Monster Egg","name":"minecraft:monster_egg"},
  {"type":97,"data":2,"description":"Stone Brick Monster Egg","name":"minecraft:monster_egg"},
  {"type":97,"data":3,"description":"Mossy Stone Brick Monster Egg","name":"minecraft:monster_egg"},
  {"type":97,"data":4,"description":"Cracked Stone Brick Monster Egg","name":"minecraft:monster_egg"},
  {"type":97,"data":5,"description":"Chiseled Stone Brick Monster Egg","name":"minecraft:monster_egg"},
  {"type":98,"data":0,"description":"Stone Bricks","name":"minecraft:stonebrick"},
  {"type":98,"data":1,"description":"Mossy Stone Bricks","name":"minecraft:stonebrick"},
  {"type":98,"data":2,"description":"Cracked Stone Bricks","name":"minecraft:stonebrick"},
  {"type":98,"data":3,"description":"Chiseled Stone Bricks","name":"minecraft:stonebrick"},
  {"type":99,"data":0,"description":"Brown Mushroom Block","name":"minecraft:brown_mushroom_block"},
  {"type":100,"data":0,"description":"Red Mushroom Block","name":"minecraft:red_mushroom_block"},
  {"type":101,"data":0,"description":"Iron Bars","name":"minecraft:iron_bars"},
  {"type":102,"data":0,"description":"Glass Pane","name":"minecraft:glass_pane"},
  {"type":103,"data":0,"description":"Melon Block","name":"minecraft:melon_block"},
  {"type":104,"data":0,"description":"Pumpkin Stem","name":"minecraft:pumpkin_stem"},
  {"type":105,"data":0,"description":"Melon Stem","name":"minecraft:melon_stem"},
  {"type":106,"data":0,"description":"Vines","name":"minecraft:vine"},
  {"type":107,"data":0,"description":"Oak Fence Gate","name":"minecraft:fence_gate"},
  {"type":108,"data":0,"description":"Brick Stairs","name":"minecraft:brick_stairs"},
  {"type":109,"data":0,"description":"Stone Brick Stairs","name":"minecraft:stone_brick_stairs"},
  {"type":110,"data":0,"description":"Mycelium","name":"minecraft:mycelium"},
  {"type":111,"data":0,"description":"Lily Pad","name":"minecraft:waterlily"},
  {"type":112,"data":0,"description":"Nether Brick","name":"minecraft:nether_brick"},
  {"type":113,"data":0,"description":"Nether Brick Fence","name":"minecraft:nether_brick_fence"},
  {"type":114,"data":0,"description":"Nether Brick Stairs","name":"minecraft:nether_brick_stairs"},
  {"type":115,"data":0,"description":"Nether Wart","name":"minecraft:nether_wart"},
  {"type":116,"data":0,"description":"Enchantment Table","name":"minecraft:enchanting_table"},
  {"type":117,"data":0,"description":"Brewing Stand","name":"minecraft:brewing_stand"},
  {"type":118,"data":0,"description":"Cauldron","name":"minecraft:cauldron"},
  {"type":119,"data":0,"description":"End Portal","name":"minecraft:end_portal"},
  {"type":120,"data":0,"description":"End Portal Frame","name":"minecraft:end_portal_frame"},
  {"type":121,"data":0,"description":"End Stone","name":"minecraft:end_stone"},
  {"type":122,"data":0,"description":"Dragon Egg","name":"minecraft:dragon_egg"},
  {"type":123,"data":0,"description":"Redstone Lamp (inactive)","name":"minecraft:redstone_lamp"},
  {"type":124,"data":0,"description":"Redstone Lamp (active)","name":"minecraft:lit_redstone_lamp"},
  {"type":125,"data":0,"description":"Double Oak Wood Slab","name":"minecraft:double_wooden_slab"},
  {"type":125,"data":1,"description":"Double Spruce Wood Slab","name":"minecraft:double_wooden_slab"},
  {"type":125,"data":2,"description":"Double Birch Wood Slab","name":"minecraft:double_wooden_slab"},
  {"type":125,"data":3,"description":"Double Jungle Wood Slab","name":"minecraft:double_wooden_slab"},
  {"type":125,"data":4,"description":"Double Acacia Wood Slab","name":"minecraft:double_wooden_slab"},
  {"type":125,"data":5,"description":"Double Dark Oak Wood Slab","name":"minecraft:double_wooden_slab"},
  {"type":126,"data":0,"description":"Oak Wood Slab","name":"minecraft:wooden_slab"},
  {"type":126,"data":1,"description":"Spruce Wood Slab","name":"minecraft:wooden_slab"},
  {"type":126,"data":2,"description":"Birch Wood Slab","name":"minecraft:wooden_slab"},
  {"type":126,"data":3,"description":"Jungle Wood Slab","name":"minecraft:wooden_slab"},
  {"type":126,"data":4,"description":"Acacia Wood Slab","name":"minecraft:wooden_slab"},
  {"type":126,"data":5,"description":"Dark Oak Wood Slab","name":"minecraft:wooden_slab"},
  {"type":127,"data":0,"description":"Cocoa","name":"minecraft:cocoa"},
  {"type":128,"data":0,"description":"Sandstone Stairs","name":"minecraft:sandstone_stairs"},
  {"type":129,"data":0,"description":"Emerald Ore","name":"minecraft:emerald_ore"},
  {"type":130,"data":0,"description":"Ender Chest","name":"minecraft:ender_chest"},
  {"type":131,"data":0,"description":"Tripwire Hook","name":"minecraft:tripwire_hook"},
  {"type":132,"data":0,"description":"Tripwire","name":"minecraft:tripwire_hook"},
  {"type":133,"data":0,"description":"Emerald Block","name":"minecraft:emerald_block"},
  {"type":134,"data":0,"description":"Spruce Wood Stairs","name":"minecraft:spruce_stairs"},
  {"type":135,"data":0,"description":"Birch Wood Stairs","name":"minecraft:birch_stairs"},
  {"type":136,"data":0,"description":"Jungle Wood Stairs","name":"minecraft:jungle_stairs"},
  {"type":137,"data":0,"description":"Command Block","name":"minecraft:command_block"},
  {"type":138,"data":0,"description":"Beacon","name":"minecraft:beacon"},
  {"type":139,"data":0,"description":"Cobblestone Wall","name":"minecraft:cobblestone_wall"},
  {"type":139,"data":1,"description":"Mossy Cobblestone Wall","name":"minecraft:cobblestone_wall"},
  {"type":140,"data":0,"description":"Flower Pot","name":"minecraft:flower_pot"},
  {"type":141,"data":0,"description":"Carrots","name":"minecraft:carrots"},
  {"type":142,"data":0,"description":"Potatoes","name":"minecraft:potatoes"},
  {"type":143,"data":0,"description":"Wooden Button","name":"minecraft:wooden_button"},
  {"type":144,"data":0,"description":"Mob Head","name":"minecraft:skull"},
  {"type":145,"data":0,"description":"Anvil","name":"minecraft:anvil"},
  {"type":146,"data":0,"description":"Trapped Chest","name":"minecraft:trapped_chest"},
  {"type":147,"data":0,"description":"Weighted Pressure Plate (light)","name":"minecraft:light_weighted_pressure_plate"},
  {"type":148,"data":0,"description":"Weighted Pressure Plate (heavy)","name":"minecraft:heavy_weighted_pressure_plate"},
  {"type":149,"data":0,"description":"Redstone Comparator (inactive)","name":"minecraft:unpowered_comparator"},
  {"type":150,"data":0,"description":"Redstone Comparator (active)","name":"minecraft:powered_comparator"},
  {"type":151,"data":0,"description":"Daylight Sensor","name":"minecraft:daylight_detector"},
  {"type":152,"data":0,"description":"Redstone Block","name":"minecraft:redstone_block"},
  {"type":153,"data":0,"description":"Nether Quartz Ore","name":"minecraft:quartz_ore"},
  {"type":154,"data":0,"description":"Hopper","name":"minecraft:hopper"},
  {"type":155,"data":0,"description":"Quartz Block","name":"minecraft:quartz_block"},
  {"type":155,"data":1,"description":"Chiseled Quartz Block","name":"minecraft:quartz_block"},
  {"type":155,"data":2,"description":"Pillar Quartz Block","name":"minecraft:quartz_block"},
  {"type":156,"data":0,"description":"Quartz Stairs","name":"minecraft:quartz_stairs"},
  {"type":157,"data":0,"description":"Activator Rail","name":"minecraft:activator_rail"},
  {"type":158,"data":0,"description":"Dropper","name":"minecraft:dropper"},
  {"type":159,"data":0,"description":"White Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":1,"description":"Orange Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":2,"description":"Magenta Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":3,"description":"Light Blue Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":4,"description":"Yellow Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":5,"description":"Lime Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":6,"description":"Pink Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":7,"description":"Gray Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":8,"description":"Light Gray Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":9,"description":"Cyan Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":10,"description":"Purple Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":11,"description":"Blue Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":12,"description":"Brown Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":13,"description":"Green Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":14,"description":"Red Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":159,"data":15,"description":"Black Hardened Clay","name":"minecraft:stained_hardened_clay"},
  {"type":160,"data":0,"description":"White Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":1,"description":"Orange Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":2,"description":"Magenta Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":3,"description":"Light Blue Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":4,"description":"Yellow Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":5,"description":"Lime Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":6,"description":"Pink Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":7,"description":"Gray Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":8,"description":"Light Gray Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":9,"description":"Cyan Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":10,"description":"Purple Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":11,"description":"Blue Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":12,"description":"Brown Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":13,"description":"Green Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":14,"description":"Red Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":160,"data":15,"description":"Black Stained Glass Pane","name":"minecraft:stained_glass_pane"},
  {"type":161,"data":0,"description":"Acacia Leaves","name":"minecraft:leaves2"},
  {"type":161,"data":1,"description":"Dark Oak Leaves","name":"minecraft:leaves2"},
  {"type":162,"data":0,"description":"Acacia Wood","name":"minecraft:log2"},
  {"type":162,"data":1,"description":"Dark Oak Wood","name":"minecraft:log2"},
  {"type":163,"data":0,"description":"Acacia Wood Stairs","name":"minecraft:acacia_stairs"},
  {"type":164,"data":0,"description":"Dark Oak Wood Stairs","name":"minecraft:dark_oak_stairs"},
  {"type":165,"data":0,"description":"Slime Block","name":"minecraft:slime"},
  {"type":166,"data":0,"description":"Barrier","name":"minecraft:barrier"},
  {"type":167,"data":0,"description":"Iron Trapdoor","name":"minecraft:iron_trapdoor"},
  {"type":168,"data":0,"description":"Prismarine","name":"minecraft:prismarine"},
  {"type":168,"data":1,"description":"Prismarine Bricks","name":"minecraft:prismarine"},
  {"type":168,"data":2,"description":"Dark Prismarine","name":"minecraft:prismarine"},
  {"type":169,"data":0,"description":"Sea Lantern","name":"minecraft:sea_lantern"},
  {"type":170,"data":0,"description":"Hay Bale","name":"minecraft:hay_block"},
  {"type":171,"data":0,"description":"White Carpet","name":"minecraft:carpet"},
  {"type":171,"data":1,"description":"Orange Carpet","name":"minecraft:carpet"},
  {"type":171,"data":2,"description":"Magenta Carpet","name":"minecraft:carpet"},
  {"type":171,"data":3,"description":"Light Blue Carpet","name":"minecraft:carpet"},
  {"type":171,"data":4,"description":"Yellow Carpet","name":"minecraft:carpet"},
  {"type":171,"data":5,"description":"Lime Carpet","name":"minecraft:carpet"},
  {"type":171,"data":6,"description":"Pink Carpet","name":"minecraft:carpet"},
  {"type":171,"data":7,"description":"Gray Carpet","name":"minecraft:carpet"},
  {"type":171,"data":8,"description":"Light Gray Carpet","name":"minecraft:carpet"},
  {"type":171,"data":9,"description":"Cyan Carpet","name":"minecraft:carpet"},
  {"type":171,"data":10,"description":"Purple Carpet","name":"minecraft:carpet"},
  {"type":171,"data":11,"description":"Blue Carpet","name":"minecraft:carpet"},
  {"type":171,"data":12,"description":"Brown Carpet","name":"minecraft:carpet"},
  {"type":171,"data":13,"description":"Green Carpet","name":"minecraft:carpet"},
  {"type":171,"data":14,"description":"Red Carpet","name":"minecraft:carpet"},
  {"type":171,"data":15,"description":"Black Carpet","name":"minecraft:carpet"},
  {"type":172,"data":0,"description":"Hardened Clay","name":"minecraft:hardened_clay"},
  {"type":173,"data":0,"description":"Block of Coal","name":"minecraft:coal_block"},
  {"type":174,"data":0,"description":"Packed Ice","name":"minecraft:packed_ice"},
  {"type":175,"data":0,"description":"Sunflower","name":"minecraft:double_plant"},
  {"type":175,"data":1,"description":"Lilac","name":"minecraft:double_plant"},
  {"type":175,"data":2,"description":"Double Tallgrass","name":"minecraft:double_plant"},
  {"type":175,"data":3,"description":"Large Fern","name":"minecraft:double_plant"},
  {"type":175,"data":4,"description":"Rose Bush","name":"minecraft:double_plant"},
  {"type":175,"data":5,"description":"Peony","name":"minecraft:double_plant"},
  {"type":176,"data":0,"description":"Free-standing Banner","name":"minecraft:standing_banner"},
  {"type":177,"data":0,"description":"Wall-mounted Banner","name":"minecraft:wall_banner"},
  {"type":178,"data":0,"description":"Inverted Daylight Sensor","name":"minecraft:daylight_detector_inverted"},
  {"type":179,"data":0,"description":"Red Sandstone","name":"minecraft:red_sandstone"},
  {"type":179,"data":1,"description":"Chiseled Red Sandstone","name":"minecraft:red_sandstone"},
  {"type":179,"data":2,"description":"Smooth Red Sandstone","name":"minecraft:red_sandstone"},
  {"type":180,"data":0,"description":"Red Sandstone Stairs","name":"minecraft:red_sandstone_stairs"},
  {"type":181,"data":0,"description":"Double Red Sandstone Slab","name":"minecraft:double_stone_slab2"},
  {"type":182,"data":0,"description":"Red Sandstone Slab","name":"minecraft:stone_slab2"},
  {"type":183,"data":0,"description":"Spruce Fence Gate","name":"minecraft:spruce_fence_gate"},
  {"type":184,"data":0,"description":"Birch Fence Gate","name":"minecraft:birch_fence_gate"},
  {"type":185,"data":0,"description":"Jungle Fence Gate","name":"minecraft:jungle_fence_gate"},
  {"type":186,"data":0,"description":"Dark Oak Fence Gate","name":"minecraft:dark_oak_fence_gate"},
  {"type":187,"data":0,"description":"Acacia Fence Gate","name":"minecraft:acacia_fence_gate"},
  {"type":188,"data":0,"description":"Spruce Fence","name":"minecraft:spruce_fence"},
  {"type":189,"data":0,"description":"Birch Fence","name":"minecraft:birch_fence"},
  {"type":190,"data":0,"description":"Jungle Fence","name":"minecraft:jungle_fence"},
  {"type":191,"data":0,"description":"Dark Oak Fence","name":"minecraft:dark_oak_fence"},
  {"type":192,"data":0,"description":"Acacia Fence","name":"minecraft:acacia_fence"},
  {"type":193,"data":0,"description":"Spruce Door Block","name":"minecraft:spruce_door"},
  {"type":194,"data":0,"description":"Birch Door Block","name":"minecraft:birch_door"},
  {"type":195,"data":0,"description":"Jungle Door Block","name":"minecraft:jungle_door"},
  {"type":196,"data":0,"description":"Acacia Door Block","name":"minecraft:acacia_door"},
  {"type":197,"data":0,"description":"Dark Oak Door Block","name":"minecraft:dark_oak_door"},
  {"type":198,"data":0,"description":"End Rod","name":"minecraft:end_rod"},
  {"type":199,"data":0,"description":"Chorus Plant","name":"minecraft:chorus_plant"},
  {"type":200,"data":0,"description":"Chorus Flower","name":"minecraft:chorus_flower"},
  {"type":201,"data":0,"description":"Purpur Block","name":"minecraft:purpur_block"},
  {"type":202,"data":0,"description":"Purpur Pillar","name":"minecraft:purpur_pillar"},
  {"type":203,"data":0,"description":"Purpur Stairs","name":"minecraft:purpur_stairs"},
  {"type":204,"data":0,"description":"Purpur Double Slab","name":"minecraft:purpur_double_slab"},
  {"type":205,"data":0,"description":"Purpur Slab","name":"minecraft:purpur_slab"},
  {"type":206,"data":0,"description":"End Stone Bricks","name":"minecraft:end_bricks"},
  {"type":207,"data":0,"description":"Beetroot Block","name":"minecraft:beetroots"},
  {"type":208,"data":0,"description":"Grass Path","name":"minecraft:grass_path"},
  {"type":209,"data":0,"description":"End Gateway","name":"minecraft:end_gateway"},
  {"type":210,"data":0,"description":"Repeating Command Block","name":"minecraft:repeating_command_block"},
  {"type":211,"data":0,"description":"Chain Command Block","name":"minecraft:chain_command_block"},
  {"type":212,"data":0,"description":"Frosted Ice","name":"minecraft:frosted_ice"},
  {"type":213,"data":0,"description":"Magma Block","name":"minecraft:magma"},
  {"type":214,"data":0,"description":"Nether Wart Block","name":"minecraft:nether_wart_block"},
  {"type":215,"data":0,"description":"Red Nether Brick","name":"minecraft:red_nether_brick"},
  {"type":216,"data":0,"description":"Bone Block","name":"minecraft:bone_block"},
  {"type":217,"data":0,"description":"Structure Void","name":"minecraft:structure_void"},
  {"type":218,"data":0,"description":"Observer","name":"minecraft:observer"},
  {"type":219,"data":0,"description":"White Shulker Box","name":"minecraft:white_shulker_box"},
  {"type":220,"data":0,"description":"Orange Shulker Box","name":"minecraft:orange_shulker_box"},
  {"type":221,"data":0,"description":"Magenta Shulker Box","name":"minecraft:magenta_shulker_box"},
  {"type":222,"data":0,"description":"Light Blue Shulker Box","name":"minecraft:light_blue_shulker_box"},
  {"type":223,"data":0,"description":"Yellow Shulker Box","name":"minecraft:yellow_shulker_box"},
  {"type":224,"data":0,"description":"Lime Shulker Box","name":"minecraft:lime_shulker_box"},
  {"type":225,"data":0,"description":"Pink Shulker Box","name":"minecraft:pink_shulker_box"},
  {"type":226,"data":0,"description":"Gray Shulker Box","name":"minecraft:gray_shulker_box"},
  {"type":227,"data":0,"description":"Light Gray Shulker Box","name":"minecraft:silver_shulker_box"},
  {"type":228,"data":0,"description":"Cyan Shulker Box","name":"minecraft:cyan_shulker_box"},
  {"type":229,"data":0,"description":"Purple Shulker Box","name":"minecraft:purple_shulker_box"},
  {"type":230,"data":0,"description":"Blue Shulker Box","name":"minecraft:blue_shulker_box"},
  {"type":231,"data":0,"description":"Brown Shulker Box","name":"minecraft:brown_shulker_box"},
  {"type":232,"data":0,"description":"Green Shulker Box","name":"minecraft:green_shulker_box"},
  {"type":233,"data":0,"description":"Red Shulker Box","name":"minecraft:red_shulker_box"},
  {"type":234,"data":0,"description":"Black Shulker Box","name":"minecraft:black_shulker_box"},
  {"type":235,"data":0,"description":"White Glazed Terracotta","name":"minecraft:white_glazed_terracotta"},
  {"type":236,"data":0,"description":"Orange Glazed Terracotta","name":"minecraft:orange_glazed_terracotta"},
  {"type":237,"data":0,"description":"Magenta Glazed Terracotta","name":"minecraft:magenta_glazed_terracotta"},
  {"type":238,"data":0,"description":"Light Blue Glazed Terracotta","name":"minecraft:light_blue_glazed_terracotta"},
  {"type":239,"data":0,"description":"Yellow Glazed Terracotta","name":"minecraft:yellow_glazed_terracotta"},
  {"type":240,"data":0,"description":"Lime Glazed Terracotta","name":"minecraft:lime_glazed_terracotta"},
  {"type":241,"data":0,"description":"Pink Glazed Terracotta","name":"minecraft:pink_glazed_terracotta"},
  {"type":242,"data":0,"description":"Gray Glazed Terracotta","name":"minecraft:gray_glazed_terracotta"},
  {"type":243,"data":0,"description":"Light Gray Glazed Terracotta","name":"minecraft:light_gray_glazed_terracotta"},
  {"type":244,"data":0,"description":"Cyan Glazed Terracotta","name":"minecraft:cyan_glazed_terracotta"},
  {"type":245,"data":0,"description":"Purple Glazed Terracotta","name":"minecraft:purple_glazed_terracotta"},
  {"type":246,"data":0,"description":"Blue Glazed Terracotta","name":"minecraft:blue_glazed_terracotta"},
  {"type":247,"data":0,"description":"Brown Glazed Terracotta","name":"minecraft:brown_glazed_terracotta"},
  {"type":248,"data":0,"description":"Green Glazed Terracotta","name":"minecraft:green_glazed_terracotta"},
  {"type":249,"data":0,"description":"Red Glazed Terracotta","name":"minecraft:red_glazed_terracotta"},
  {"type":250,"data":0,"description":"Black Glazed Terracotta","name":"minecraft:black_glazed_terracotta"},
  {"type":251,"data":0,"description":"White Concrete","name":"minecraft:concrete"},
  {"type":251,"data":1,"description":"Orange Concrete","name":"minecraft:concrete"},
  {"type":251,"data":2,"description":"Magenta Concrete","name":"minecraft:concrete"},
  {"type":251,"data":3,"description":"Light Blue Concrete","name":"minecraft:concrete"},
  {"type":251,"data":4,"description":"Yellow Concrete","name":"minecraft:concrete"},
  {"type":251,"data":5,"description":"Lime Concrete","name":"minecraft:concrete"},
  {"type":251,"data":6,"description":"Pink Concrete","name":"minecraft:concrete"},
  {"type":251,"data":7,"description":"Gray Concrete","name":"minecraft:concrete"},
  {"type":251,"data":8,"description":"Light Gray Concrete","name":"minecraft:concrete"},
  {"type":251,"data":9,"description":"Cyan Concrete","name":"minecraft:concrete"},
  {"type":251,"data":10,"description":"Purple Concrete","name":"minecraft:concrete"},
  {"type":251,"data":11,"description":"Blue Concrete","name":"minecraft:concrete"},
  {"type":251,"data":12,"description":"Brown Concrete","name":"minecraft:concrete"},
  {"type":251,"data":13,"description":"Green Concrete","name":"minecraft:concrete"},
  {"type":251,"data":14,"description":"Red Concrete","name":"minecraft:concrete"},
  {"type":251,"data":15,"description":"Black Concrete","name":"minecraft:concrete"},
  {"type":252,"data":0,"description":"White Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":1,"description":"Orange Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":2,"description":"Magenta Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":3,"description":"Light Blue Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":4,"description":"Yellow Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":5,"description":"Lime Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":6,"description":"Pink Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":7,"description":"Gray Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":8,"description":"Light Gray Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":9,"description":"Cyan Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":10,"description":"Purple Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":11,"description":"Blue Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":12,"description":"Brown Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":13,"description":"Green Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":14,"description":"Red Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":252,"data":15,"description":"Black Concrete Powder","name":"minecraft:concrete_powder"},
  {"type":255,"data":0,"description":"Structure Block","name":"minecraft:structure_block"},
  {"type":256,"data":0,"description":"Iron Shovel","name":"minecraft:iron_shovel"},
  {"type":257,"data":0,"description":"Iron Pickaxe","name":"minecraft:iron_pickaxe"},
  {"type":258,"data":0,"description":"Iron Axe","name":"minecraft:iron_axe"},
  {"type":259,"data":0,"description":"Flint and Steel","name":"minecraft:flint_and_steel"},
  {"type":260,"data":0,"description":"Apple","name":"minecraft:apple"},
  {"type":261,"data":0,"description":"Bow","name":"minecraft:bow"},
  {"type":262,"data":0,"description":"Arrow","name":"minecraft:arrow"},
  {"type":263,"data":0,"description":"Coal","name":"minecraft:coal"},
  {"type":263,"data":1,"description":"Charcoal","name":"minecraft:coal"},
  {"type":264,"data":0,"description":"Diamond","name":"minecraft:diamond"},
  {"type":265,"data":0,"description":"Iron Ingot","name":"minecraft:iron_ingot"},
  {"type":266,"data":0,"description":"Gold Ingot","name":"minecraft:gold_ingot"},
  {"type":267,"data":0,"description":"Iron Sword","name":"minecraft:iron_sword"},
  {"type":268,"data":0,"description":"Wooden Sword","name":"minecraft:wooden_sword"},
  {"type":269,"data":0,"description":"Wooden Shovel","name":"minecraft:wooden_shovel"},
  {"type":270,"data":0,"description":"Wooden Pickaxe","name":"minecraft:wooden_pickaxe"},
  {"type":271,"data":0,"description":"Wooden Axe","name":"minecraft:wooden_axe"},
  {"type":272,"data":0,"description":"Stone Sword","name":"minecraft:stone_sword"},
  {"type":273,"data":0,"description":"Stone Shovel","name":"minecraft:stone_shovel"},
  {"type":274,"data":0,"description":"Stone Pickaxe","name":"minecraft:stone_pickaxe"},
  {"type":275,"data":0,"description":"Stone Axe","name":"minecraft:stone_axe"},
  {"type":276,"data":0,"description":"Diamond Sword","name":"minecraft:diamond_sword"},
  {"type":277,"data":0,"description":"Diamond Shovel","name":"minecraft:diamond_shovel"},
  {"type":278,"data":0,"description":"Diamond Pickaxe","name":"minecraft:diamond_pickaxe"},
  {"type":279,"data":0,"description":"Diamond Axe","name":"minecraft:diamond_axe"},
  {"type":280,"data":0,"description":"Stick","name":"minecraft:stick"},
  {"type":281,"data":0,"description":"Bowl","name":"minecraft:bowl"},
  {"type":282,"data":0,"description":"Mushroom Stew","name":"minecraft:mushroom_stew"},
  {"type":283,"data":0,"description":"Golden Sword","name":"minecraft:golden_sword"},
  {"type":284,"data":0,"description":"Golden Shovel","name":"minecraft:golden_shovel"},
  {"type":285,"data":0,"description":"Golden Pickaxe","name":"minecraft:golden_pickaxe"},
  {"type":286,"data":0,"description":"Golden Axe","name":"minecraft:golden_axe"},
  {"type":287,"data":0,"description":"String","name":"minecraft:string"},
  {"type":288,"data":0,"description":"Feather","name":"minecraft:feather"},
  {"type":289,"data":0,"description":"Gunpowder","name":"minecraft:gunpowder"},
  {"type":290,"data":0,"description":"Wooden Hoe","name":"minecraft:wooden_hoe"},
  {"type":291,"data":0,"description":"Stone Hoe","name":"minecraft:stone_hoe"},
  {"type":292,"data":0,"description":"Iron Hoe","name":"minecraft:iron_hoe"},
  {"type":293,"data":0,"description":"Diamond Hoe","name":"minecraft:diamond_hoe"},
  {"type":294,"data":0,"description":"Golden Hoe","name":"minecraft:golden_hoe"},
  {"type":295,"data":0,"description":"Wheat Seeds","name":"minecraft:wheat_seeds"},
  {"type":296,"data":0,"description":"Wheat","name":"minecraft:wheat"},
  {"type":297,"data":0,"description":"Bread","name":"minecraft:bread"},
  {"type":298,"data":0,"description":"Leather Helmet","name":"minecraft:leather_helmet"},
  {"type":299,"data":0,"description":"Leather Tunic","name":"minecraft:leather_chestplate"},
  {"type":300,"data":0,"description":"Leather Pants","name":"minecraft:leather_leggings"},
  {"type":301,"data":0,"description":"Leather Boots","name":"minecraft:leather_boots"},
  {"type":302,"data":0,"description":"Chainmail Helmet","name":"minecraft:chainmail_helmet"},
  {"type":303,"data":0,"description":"Chainmail Chestplate","name":"minecraft:chainmail_chestplate"},
  {"type":304,"data":0,"description":"Chainmail Leggings","name":"minecraft:chainmail_leggings"},
  {"type":305,"data":0,"description":"Chainmail Boots","name":"minecraft:chainmail_boots"},
  {"type":306,"data":0,"description":"Iron Helmet","name":"minecraft:iron_helmet"},
  {"type":307,"data":0,"description":"Iron Chestplate","name":"minecraft:iron_chestplate"},
  {"type":308,"data":0,"description":"Iron Leggings","name":"minecraft:iron_leggings"},
  {"type":309,"data":0,"description":"Iron Boots","name":"minecraft:iron_boots"},
  {"type":310,"data":0,"description":"Diamond Helmet","name":"minecraft:diamond_helmet"},
  {"type":311,"data":0,"description":"Diamond Chestplate","name":"minecraft:diamond_chestplate"},
  {"type":312,"data":0,"description":"Diamond Leggings","name":"minecraft:diamond_leggings"},
  {"type":313,"data":0,"description":"Diamond Boots","name":"minecraft:diamond_boots"},
  {"type":314,"data":0,"description":"Golden Helmet","name":"minecraft:golden_helmet"},
  {"type":315,"data":0,"description":"Golden Chestplate","name":"minecraft:golden_chestplate"},
  {"type":316,"data":0,"description":"Golden Leggings","name":"minecraft:golden_leggings"},
  {"type":317,"data":0,"description":"Golden Boots","name":"minecraft:golden_boots"},
  {"type":318,"data":0,"description":"Flint","name":"minecraft:flint"},
  {"type":319,"data":0,"description":"Raw Porkchop","name":"minecraft:porkchop"},
  {"type":320,"data":0,"description":"Cooked Porkchop","name":"minecraft:cooked_porkchop"},
  {"type":321,"data":0,"description":"Painting","name":"minecraft:painting"},
  {"type":322,"data":0,"description":"Golden Apple","name":"minecraft:golden_apple"},
  {"type":322,"data":1,"description":"Enchanted Golden Apple","name":"minecraft:golden_apple"},
  {"type":323,"data":0,"description":"Sign","name":"minecraft:sign"},
  {"type":324,"data":0,"description":"Oak Door","name":"minecraft:wooden_door"},
  {"type":325,"data":0,"description":"Bucket","name":"minecraft:bucket"},
  {"type":326,"data":0,"description":"Water Bucket","name":"minecraft:water_bucket"},
  {"type":327,"data":0,"description":"Lava Bucket","name":"minecraft:lava_bucket"},
  {"type":328,"data":0,"description":"Minecart","name":"minecraft:minecart"},
  {"type":329,"data":0,"description":"Saddle","name":"minecraft:saddle"},
  {"type":330,"data":0,"description":"Iron Door","name":"minecraft:iron_door"},
  {"type":331,"data":0,"description":"Redstone","name":"minecraft:redstone"},
  {"type":332,"data":0,"description":"Snowball","name":"minecraft:snowball"},
  {"type":333,"data":0,"description":"Oak Boat","name":"minecraft:boat"},
  {"type":334,"data":0,"description":"Leather","name":"minecraft:leather"},
  {"type":335,"data":0,"description":"Milk Bucket","name":"minecraft:milk_bucket"},
  {"type":336,"data":0,"description":"Brick","name":"minecraft:brick"},
  {"type":337,"data":0,"description":"Clay","name":"minecraft:clay_ball"},
  {"type":338,"data":0,"description":"Sugar Canes","name":"minecraft:reeds"},
  {"type":339,"data":0,"description":"Paper","name":"minecraft:paper"},
  {"type":340,"data":0,"description":"Book","name":"minecraft:book"},
  {"type":341,"data":0,"description":"Slimeball","name":"minecraft:slime_ball"},
  {"type":342,"data":0,"description":"Minecart with Chest","name":"minecraft:chest_minecart"},
  {"type":343,"data":0,"description":"Minecart with Furnace","name":"minecraft:furnace_minecart"},
  {"type":344,"data":0,"description":"Egg","name":"minecraft:egg"},
  {"type":345,"data":0,"description":"Compass","name":"minecraft:compass"},
  {"type":346,"data":0,"description":"Fishing Rod","name":"minecraft:fishing_rod"},
  {"type":347,"data":0,"description":"Clock","name":"minecraft:clock"},
  {"type":348,"data":0,"description":"Glowstone Dust","name":"minecraft:glowstone_dust"},
  {"type":349,"data":0,"description":"Raw Fish","name":"minecraft:fish"},
  {"type":349,"data":1,"description":"Raw Salmon","name":"minecraft:fish"},
  {"type":349,"data":2,"description":"Clownfish","name":"minecraft:fish"},
  {"type":349,"data":3,"description":"Pufferfish","name":"minecraft:fish"},
  {"type":350,"data":0,"description":"Cooked Fish","name":"minecraft:cooked_fish"},
  {"type":350,"data":1,"description":"Cooked Salmon","name":"minecraft:cooked_fish"},
  {"type":351,"data":0,"description":"Ink Sack","name":"minecraft:dye"},
  {"type":351,"data":1,"description":"Rose Red","name":"minecraft:dye"},
  {"type":351,"data":2,"description":"Cactus Green","name":"minecraft:dye"},
  {"type":351,"data":3,"description":"Coco Beans","name":"minecraft:dye"},
  {"type":351,"data":4,"description":"Lapis Lazuli","name":"minecraft:dye"},
  {"type":351,"data":5,"description":"Purple Dye","name":"minecraft:dye"},
  {"type":351,"data":6,"description":"Cyan Dye","name":"minecraft:dye"},
  {"type":351,"data":7,"description":"Light Gray Dye","name":"minecraft:dye"},
  {"type":351,"data":8,"description":"Gray Dye","name":"minecraft:dye"},
  {"type":351,"data":9,"description":"Pink Dye","name":"minecraft:dye"},
  {"type":351,"data":10,"description":"Lime Dye","name":"minecraft:dye"},
  {"type":351,"data":11,"description":"Dandelion Yellow","name":"minecraft:dye"},
  {"type":351,"data":12,"description":"Light Blue Dye","name":"minecraft:dye"},
  {"type":351,"data":13,"description":"Magenta Dye","name":"minecraft:dye"},
  {"type":351,"data":14,"description":"Orange Dye","name":"minecraft:dye"},
  {"type":351,"data":15,"description":"Bone Meal","name":"minecraft:dye"},
  {"type":352,"data":0,"description":"Bone","name":"minecraft:bone"},
  {"type":353,"data":0,"description":"Sugar","name":"minecraft:sugar"},
  {"type":354,"data":0,"description":"Cake","name":"minecraft:cake"},
  {"type":355,"data":0,"description":"Bed","name":"minecraft:bed"},
  {"type":356,"data":0,"description":"Redstone Repeater","name":"minecraft:repeater"},
  {"type":357,"data":0,"description":"Cookie","name":"minecraft:cookie"},
  {"type":358,"data":0,"description":"Map","name":"minecraft:filled_map"},
  {"type":359,"data":0,"description":"Shears","name":"minecraft:shears"},
  {"type":360,"data":0,"description":"Melon","name":"minecraft:melon"},
  {"type":361,"data":0,"description":"Pumpkin Seeds","name":"minecraft:pumpkin_seeds"},
  {"type":362,"data":0,"description":"Melon Seeds","name":"minecraft:melon_seeds"},
  {"type":363,"data":0,"description":"Raw Beef","name":"minecraft:beef"},
  {"type":364,"data":0,"description":"Steak","name":"minecraft:cooked_beef"},
  {"type":365,"data":0,"description":"Raw Chicken","name":"minecraft:chicken"},
  {"type":366,"data":0,"description":"Cooked Chicken","name":"minecraft:cooked_chicken"},
  {"type":367,"data":0,"description":"Rotten Flesh","name":"minecraft:rotten_flesh"},
  {"type":368,"data":0,"description":"Ender Pearl","name":"minecraft:ender_pearl"},
  {"type":369,"data":0,"description":"Blaze Rod","name":"minecraft:blaze_rod"},
  {"type":370,"data":0,"description":"Ghast Tear","name":"minecraft:ghast_tear"},
  {"type":371,"data":0,"description":"Gold Nugget","name":"minecraft:gold_nugget"},
  {"type":372,"data":0,"description":"Nether Wart","name":"minecraft:nether_wart"},
  {"type":373,"data":0,"description":"Potion","name":"minecraft:potion"},
  {"type":374,"data":0,"description":"Glass Bottle","name":"minecraft:glass_bottle"},
  {"type":375,"data":0,"description":"Spider Eye","name":"minecraft:spider_eye"},
  {"type":376,"data":0,"description":"Fermented Spider Eye","name":"minecraft:fermented_spider_eye"},
  {"type":377,"data":0,"description":"Blaze Powder","name":"minecraft:blaze_powder"},
  {"type":378,"data":0,"description":"Magma Cream","name":"minecraft:magma_cream"},
  {"type":379,"data":0,"description":"Brewing Stand","name":"minecraft:brewing_stand"},
  {"type":380,"data":0,"description":"Cauldron","name":"minecraft:cauldron"},
  {"type":381,"data":0,"description":"Eye of Ender","name":"minecraft:ender_eye"},
  {"type":382,"data":0,"description":"Glistering Melon","name":"minecraft:speckled_melon"},
  {"type":383,"data":4,"description":"Spawn Elder Guardian","name":"minecraft:spawn_egg"},
  {"type":383,"data":5,"description":"Spawn Wither Skeleton","name":"minecraft:spawn_egg"},
  {"type":383,"data":6,"description":"Spawn Stray","name":"minecraft:spawn_egg"},
  {"type":383,"data":23,"description":"Spawn Husk","name":"minecraft:spawn_egg"},
  {"type":383,"data":27,"description":"Spawn Zombie Villager","name":"minecraft:spawn_egg"},
  {"type":383,"data":28,"description":"Spawn Skeleton Horse","name":"minecraft:spawn_egg"},
  {"type":383,"data":29,"description":"Spawn Zombie Horse","name":"minecraft:spawn_egg"},
  {"type":383,"data":31,"description":"Spawn Donkey","name":"minecraft:spawn_egg"},
  {"type":383,"data":32,"description":"Spawn Mule","name":"minecraft:spawn_egg"},
  {"type":383,"data":34,"description":"Spawn Evoker","name":"minecraft:spawn_egg"},
  {"type":383,"data":35,"description":"Spawn Vex","name":"minecraft:spawn_egg"},
  {"type":383,"data":36,"description":"Spawn Vindicator","name":"minecraft:spawn_egg"},
  {"type":383,"data":50,"description":"Spawn Creeper","name":"minecraft:spawn_egg"},
  {"type":383,"data":51,"description":"Spawn Skeleton","name":"minecraft:spawn_egg"},
  {"type":383,"data":52,"description":"Spawn Spider","name":"minecraft:spawn_egg"},
  {"type":383,"data":54,"description":"Spawn Zombie","name":"minecraft:spawn_egg"},
  {"type":383,"data":55,"description":"Spawn Slime","name":"minecraft:spawn_egg"},
  {"type":383,"data":56,"description":"Spawn Ghast","name":"minecraft:spawn_egg"},
  {"type":383,"data":57,"description":"Spawn Zombie Pigman","name":"minecraft:spawn_egg"},
  {"type":383,"data":58,"description":"Spawn Enderman","name":"minecraft:spawn_egg"},
  {"type":383,"data":59,"description":"Spawn Cave Spider","name":"minecraft:spawn_egg"},
  {"type":383,"data":60,"description":"Spawn Silverfish","name":"minecraft:spawn_egg"},
  {"type":383,"data":61,"description":"Spawn Blaze","name":"minecraft:spawn_egg"},
  {"type":383,"data":62,"description":"Spawn Magma Cube","name":"minecraft:spawn_egg"},
  {"type":383,"data":65,"description":"Spawn Bat","name":"minecraft:spawn_egg"},
  {"type":383,"data":66,"description":"Spawn Witch","name":"minecraft:spawn_egg"},
  {"type":383,"data":67,"description":"Spawn Endermite","name":"minecraft:spawn_egg"},
  {"type":383,"data":68,"description":"Spawn Guardian","name":"minecraft:spawn_egg"},
  {"type":383,"data":69,"description":"Spawn Shulker","name":"minecraft:spawn_egg"},
  {"type":383,"data":90,"description":"Spawn Pig","name":"minecraft:spawn_egg"},
  {"type":383,"data":91,"description":"Spawn Sheep","name":"minecraft:spawn_egg"},
  {"type":383,"data":92,"description":"Spawn Cow","name":"minecraft:spawn_egg"},
  {"type":383,"data":93,"description":"Spawn Chicken","name":"minecraft:spawn_egg"},
  {"type":383,"data":94,"description":"Spawn Squid","name":"minecraft:spawn_egg"},
  {"type":383,"data":95,"description":"Spawn Wolf","name":"minecraft:spawn_egg"},
  {"type":383,"data":96,"description":"Spawn Mooshroom","name":"minecraft:spawn_egg"},
  {"type":383,"data":98,"description":"Spawn Ocelot","name":"minecraft:spawn_egg"},
  {"type":383,"data":100,"description":"Spawn Horse","name":"minecraft:spawn_egg"},
  {"type":383,"data":101,"description":"Spawn Rabbit","name":"minecraft:spawn_egg"},
  {"type":383,"data":102,"description":"Spawn Polar Bear","name":"minecraft:spawn_egg"},
  {"type":383,"data":103,"description":"Spawn Llama","name":"minecraft:spawn_egg"},
  {"type":383,"data":120,"description":"Spawn Villager","name":"minecraft:spawn_egg"},
  {"type":384,"data":0,"description":"Bottle o' Enchanting","name":"minecraft:experience_bottle"},
  {"type":385,"data":0,"description":"Fire Charge","name":"minecraft:fire_charge"},
  {"type":386,"data":0,"description":"Book and Quill","name":"minecraft:writable_book"},
  {"type":387,"data":0,"description":"Written Book","name":"minecraft:written_book"},
  {"type":388,"data":0,"description":"Emerald","name":"minecraft:emerald"},
  {"type":389,"data":0,"description":"Item Frame","name":"minecraft:item_frame"},
  {"type":390,"data":0,"description":"Flower Pot","name":"minecraft:flower_pot"},
  {"type":391,"data":0,"description":"Carrot","name":"minecraft:carrot"},
  {"type":392,"data":0,"description":"Potato","name":"minecraft:potato"},
  {"type":393,"data":0,"description":"Baked Potato","name":"minecraft:baked_potato"},
  {"type":394,"data":0,"description":"Poisonous Potato","name":"minecraft:poisonous_potato"},
  {"type":395,"data":0,"description":"Empty Map","name":"minecraft:map"},
  {"type":396,"data":0,"description":"Golden Carrot","name":"minecraft:golden_carrot"},
  {"type":397,"data":0,"description":"Mob Head (Skeleton)","name":"minecraft:skull"},
  {"type":397,"data":1,"description":"Mob Head (Wither Skeleton)","name":"minecraft:skull"},
  {"type":397,"data":2,"description":"Mob Head (Zombie)","name":"minecraft:skull"},
  {"type":397,"data":3,"description":"Mob Head (Human)","name":"minecraft:skull"},
  {"type":397,"data":4,"description":"Mob Head (Creeper)","name":"minecraft:skull"},
  {"type":397,"data":5,"description":"Mob Head (Dragon)","name":"minecraft:skull"},
  {"type":398,"data":0,"description":"Carrot on a Stick","name":"minecraft:carrot_on_a_stick"},
  {"type":399,"data":0,"description":"Nether Star","name":"minecraft:nether_star"},
  {"type":400,"data":0,"description":"Pumpkin Pie","name":"minecraft:pumpkin_pie"},
  {"type":401,"data":0,"description":"Firework Rocket","name":"minecraft:fireworks"},
  {"type":402,"data":0,"description":"Firework Star","name":"minecraft:firework_charge"},
  {"type":403,"data":0,"description":"Enchanted Book","name":"minecraft:enchanted_book"},
  {"type":404,"data":0,"description":"Redstone Comparator","name":"minecraft:comparator"},
  {"type":405,"data":0,"description":"Nether Brick","name":"minecraft:netherbrick"},
  {"type":406,"data":0,"description":"Nether Quartz","name":"minecraft:quartz"},
  {"type":407,"data":0,"description":"Minecart with TNT","name":"minecraft:tnt_minecart"},
  {"type":408,"data":0,"description":"Minecart with Hopper","name":"minecraft:hopper_minecart"},
  {"type":409,"data":0,"description":"Prismarine Shard","name":"minecraft:prismarine_shard"},
  {"type":410,"data":0,"description":"Prismarine Crystals","name":"minecraft:prismarine_crystals"},
  {"type":411,"data":0,"description":"Raw Rabbit","name":"minecraft:rabbit"},
  {"type":412,"data":0,"description":"Cooked Rabbit","name":"minecraft:cooked_rabbit"},
  {"type":413,"data":0,"description":"Rabbit Stew","name":"minecraft:rabbit_stew"},
  {"type":414,"data":0,"description":"Rabbit's Foot","name":"minecraft:rabbit_foot"},
  {"type":415,"data":0,"description":"Rabbit Hide","name":"minecraft:rabbit_hide"},
  {"type":416,"data":0,"description":"Armor Stand","name":"minecraft:armor_stand"},
  {"type":417,"data":0,"description":"Iron Horse Armor","name":"minecraft:iron_horse_armor"},
  {"type":418,"data":0,"description":"Golden Horse Armor","name":"minecraft:golden_horse_armor"},
  {"type":419,"data":0,"description":"Diamond Horse Armor","name":"minecraft:diamond_horse_armor"},
  {"type":420,"data":0,"description":"Lead","name":"minecraft:lead"},
  {"type":421,"data":0,"description":"Name Tag","name":"minecraft:name_tag"},
  {"type":422,"data":0,"description":"Minecart with Command Block","name":"minecraft:command_block_minecart"},
  {"type":423,"data":0,"description":"Raw Mutton","name":"minecraft:mutton"},
  {"type":424,"data":0,"description":"Cooked Mutton","name":"minecraft:cooked_mutton"},
  {"type":425,"data":0,"description":"Banner","name":"minecraft:banner"},
  {"type":427,"data":0,"description":"Spruce Door","name":"minecraft:spruce_door"},
  {"type":428,"data":0,"description":"Birch Door","name":"minecraft:birch_door"},
  {"type":429,"data":0,"description":"Jungle Door","name":"minecraft:jungle_door"},
  {"type":430,"data":0,"description":"Acacia Door","name":"minecraft:acacia_door"},
  {"type":431,"data":0,"description":"Dark Oak Door","name":"minecraft:dark_oak_door"},
  {"type":432,"data":0,"description":"Chorus Fruit","name":"minecraft:chorus_fruit"},
  {"type":433,"data":0,"description":"Popped Chorus Fruit","name":"minecraft:popped_chorus_fruit"},
  {"type":434,"data":0,"description":"Beetroot","name":"minecraft:beetroot"},
  {"type":435,"data":0,"description":"Beetroot Seeds","name":"minecraft:beetroot_seeds"},
  {"type":436,"data":0,"description":"Beetroot Soup","name":"minecraft:beetroot_soup"},
  {"type":437,"data":0,"description":"Dragon's Breath","name":"minecraft:dragon_breath"},
  {"type":438,"data":0,"description":"Splash Potion","name":"minecraft:splash_potion"},
  {"type":439,"data":0,"description":"Spectral Arrow","name":"minecraft:spectral_arrow"},
  {"type":440,"data":0,"description":"Tipped Arrow","name":"minecraft:tipped_arrow"},
  {"type":441,"data":0,"description":"Lingering Potion","name":"minecraft:lingering_potion"},
  {"type":442,"data":0,"description":"Shield","name":"minecraft:shield"},
  {"type":443,"data":0,"description":"Elytra","name":"minecraft:elytra"},
  {"type":444,"data":0,"description":"Spruce Boat","name":"minecraft:spruce_boat"},
  {"type":445,"data":0,"description":"Birch Boat","name":"minecraft:birch_boat"},
  {"type":446,"data":0,"description":"Jungle Boat","name":"minecraft:jungle_boat"},
  {"type":447,"data":0,"description":"Acacia Boat","name":"minecraft:acacia_boat"},
  {"type":448,"data":0,"description":"Dark Oak Boat","name":"minecraft:dark_oak_boat"},
  {"type":449,"data":0,"description":"Totem of Undying","name":"minecraft:totem_of_undying"},
  {"type":450,"data":0,"description":"Shulker Shell","name":"minecraft:shulker_shell"},
  {"type":452,"data":0,"description":"Iron Nugget","name":"minecraft:iron_nugget"},
  {"type":2256,"data":0,"description":"13 Disc","name":"minecraft:record_13"},
  {"type":2257,"data":0,"description":"Cat Disc","name":"minecraft:record_cat"},
  {"type":2258,"data":0,"description":"Blocks Disc","name":"minecraft:record_blocks"},
  {"type":2259,"data":0,"description":"Chirp Disc","name":"minecraft:record_chirp"},
  {"type":2260,"data":0,"description":"Far Disc","name":"minecraft:record_far"},
  {"type":2261,"data":0,"description":"Mall Disc","name":"minecraft:record_mall"},
  {"type":2262,"data":0,"description":"Mellohi Disc","name":"minecraft:record_mellohi"},
  {"type":2263,"data":0,"description":"Stal Disc","name":"minecraft:record_stal"},
  {"type":2264,"data":0,"description":"Strad Disc","name":"minecraft:record_strad"},
  {"type":2265,"data":0,"description":"Ward Disc","name":"minecraft:record_ward"},
  {"type":2266,"data":0,"description":"11 Disc","name":"minecraft:record_11"},
  {"type":2267,"data":0,"description":"Wait Disc","name":"minecraft:record_wait"}
];
